CompatibilityFeatures
lukaszjdrzewiecki/bicycles-service pull request #11
Opened 2019-02-28 16:02 UTC by filipdrzewiecki

CompatibilityFeatures

2019-02-28 21:56 UTC, lukaszjdrzewiecki requested changes

2019-02-28 21:56 UTC, lukaszjdrzewiecki commented on src/main/java/p76/bicycles/dto/Hub.java
> +
Formatuj koD!!!!!!!!!!!!!!!!!!!!!!!!!

2019-02-28 21:56 UTC, lukaszjdrzewiecki commented on src/main/java/p76/bicycles/dto/RearWheel.java
> +public class RearWheel extends BicyclePart{
Formatuj kod!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!11

2019-02-28 21:56 UTC, lukaszjdrzewiecki commented on src/main/java/p76/bicycles/dto/Rim.java
> +public class Rim {
Formatuj kod!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!11

2019-02-28 21:56 UTC, lukaszjdrzewiecki commented on src/main/java/p76/bicycles/service/BicycleCompatibility.java
> +        for(int i : integers) if(!(i == a)) return false;
Formatuj kod!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!11

po for zawsze dodwaj klamry
tak samo po if

2019-02-28 21:56 UTC, lukaszjdrzewiecki commented on src/main/java/p76/bicycles/service/BicycleCompatibility.java
> +    public void wheelCheck (Bicycle bicycle){
Formatuj kod!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!11

2019-02-28 21:56 UTC, lukaszjdrzewiecki commented on src/main/java/p76/bicycles/service/BicycleCompatibility.java
> +    public void wheelCheck (Bicycle bicycle){
jeżeli metoda coś ma sprawdzić, to fajnie jak zwróci wynik sprawdzenia, a nie wydrukuje to na konsole. Co jak będziesz chciał wynik zapisać do pliku i do bazy jednocześnie?

2019-02-28 21:56 UTC, lukaszjdrzewiecki commented on src/main/java/p76/bicycles/service/BicycleCompatibility.java
> +    public void bicycleCheck (Bicycle bicycle){
Formatuj kod!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!11

2019-02-28 21:56 UTC, lukaszjdrzewiecki commented on src/main/java/p76/bicycles/service/BicycleCompatibility.java
> +        System.out.println("[GENERAL COMPATIBILITY CHECK]");
podobnie jak powyzej. Zwróc wynik sprawdzenia i w osobnej metodzie to wydrukuj. Ta metoda wyłamuje się z zasaday SOLID. Robi dwie rzeczy - sprawdza oraz drukuje. Nie jesteś w stanie napisać do niej testuj jednostkowego. Jakby metoda zwróciła wynik, a inna metoda by to drukowała, byłbyś w stanie napisać test. Generalnie jeżeli do metody nie da się napisać testu, to znaczy, że jest źle zaprojektowana.

2019-02-28 22:02 UTC, lukaszjdrzewiecki requested changes

2019-02-28 22:02 UTC, lukaszjdrzewiecki commented on src/main/java/p76/bicycles/service/BicycleCompatibility.java
> +    public boolean drivetrainCheck(Bicycle bicycle) {
metoda, która zwraca boolean powinna sie nazywac isDrivetrainCheck
Zawsze is*

2019-02-28 22:02 UTC, lukaszjdrzewiecki commented on src/main/java/p76/bicycles/service/BicycleCompatibility.java
> +    public void drivetrainCheckPrint(Bicycle bicycle) {
to sie nie wiele zmieniło od poprzedniego razu
metoda drivetrainCheck powinna zwracać komunikat do wydrukowania. Najlepiej jakbyś to opakował w jakąś klasę z resultatem i komunikatem

2019-03-01 10:16 UTC, filipdrzewiecki commented on src/main/java/p76/bicycles/service/BicycleCompatibility.java
> +    public boolean drivetrainCheck(Bicycle bicycle) {
Ponawiam pytanie: czy takie jest naming conventions? Widziałem masę metod, również tych wbudowanych w Javę, które zwracały boolean, a żadna z nich nie miała IS. Poza tym isDrivetrainCheck może być mylące, bo niezależnie od wyniku trye/false, to zawsze będzie DrivetrainCheck. Jeśli trzeba dodać "is" to lepiej byłoby również zmienić nazwę całej metody na "isDrivetrainCompatible"

2019-03-01 10:19 UTC, filipdrzewiecki commented
Całość formatowania, którą requestowałeś, jest już zrobiona. Dalej pytanie: co z nazwami metod i jaki masz pomysł na rozwiązanie tego za pomocą interfejsu?

2019-03-04 12:20 UTC, merged